### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [panosdim/mdv#1]
Dear @panosdim,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by panosdim** [comment]
It is not possible to generate an .exe as the program is using ncruses library which is available only for Unix/Linux OS.

**Comment by sergeevabc** [comment]
For Windows, I’m told [PDCurses][1] suggested to be used instead of nCurses. 

[1]: https://github.com/wmcbrine/PDCurses

**Comment by panosdim** [comment]
My first priority is to finish the code for linux and nCurses. Then i will check if i can make a conversion from nCurses to PDCurses.
